// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtcgivretwpnccclwhtu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10Y2dpdnJldHdwbmNjY2x3aHR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjA2NzcsImV4cCI6MjA2MjAzNjY3N30.zCPyRVhDWva0ZpW5wBUOltYUe3LxK4lBcDau-M-OgQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);